
export const SET_THEME = "SET_THEME";
export const MAERKET_CONFIG_LIST = "MAERKET_CONFIG_LIST";
export const GET_GROUPS = "GET_GROUPS";
export const GET_DRAG_VAL ="GET_DRAG_VAL";
export const GET_CORE_PRICE_LIST = "CORE_PRICE_LIST";
export const GET_CORE_PRICE_BY_ID = "GET_CORE_PRICE_BY_ID";
export const CHANGE_SOURCE_INIT_STATUS = "CHANGE_SOURCE_INIT_STATUS";
export const SAVE_CORE_PRICE = "SAVE_CORE_PRICE";
export const CREATE_CORE_PRICE = "CREATE_CORE_PRICE";
export const CORE_PRICE_MAERKET_CONFIG_LIST = "CORE_PRICE_MAERKET_CONFIG_LIST";
export const DELETE_CORE_PRICE = "DELETE_CORE_PRICE";
export const CREATE_GROUPS = "CREATE_GROUPS";
export const UPDATE_GROUPS = "UPDATE_GROUPS";
export const DELETE_GROUPS = "DELETE_GROUPS";
export const SAVE_TR = "SAVE_TR";
export const SAVE_PRICING_LIST = "SAVE_PRICING_LIST";
export const FIND_PRICING_LIST = "FIND_PRICING_LIST";
export const DELETE_PRICING_LIST = "DELETE_PRICING_LIST";


//market price
export const SAVE_CONFIG_DADA = "SAVE_CONFIG_DADA";

//marketDetail
export const MARKET_PAGE_EX ="MARKET_PAGE_EX";
export const GET_SYMBOLLIST ="GET_SYMBOLLIST";
export const SAVE_PARAM ="SAVE_PARAM";
export const START_INSTANCE ="START_INSTANCE";
export const SAVE_SOCKET ="SAVE_SOCKET";
export const SAVE_SOCKET_INSTANCEOUTPUT ="SAVE_SOCKET_INSTANCEOUTPUT";
export const COUNTER_PARTY ="COUNTER_PARTY";
export const COUNTER_PARTY_DRAG ="COUNTER_PARTY_DRAG";
export const COUNTER_PARTY_SAVE ="COUNTER_PARTY_SAVE";

export const SAVE_MINTICK ="SAVE_MINTICK";
export const SAVE_APPLY_BTN ="SAVE_APPLY_BTN";

//check login
export const MARKET_LOGIN ="MARKET_LOGIN";
export const MARKET_POST_LOGIN ="MARKET_POST_LOGIN";

//distribution
export const GET_DISTRIBUTION_LIST_BY_INSTANCE_ID = "GET_DISTRIBUTION_LIST_BY_INSTANCE_ID";
export const SAVE_DISTRIBUTION = "SAVE_DISTRIBUTION";
export const ADD_DISTRIBUTION = "ADD_DISTRIBUTION";
export const DELETE_DISTRIBUTION_BY_ID = "DELETE_DISTRIBUTION_BY_ID";
export const SAVE_QUOTE = "SAVE_QUOTE";
export const GET_QUOTE_SOURCE_LIST = "GET_QUOTE_SOURCE_LIST";

//reference price
export const GET_REFERENCE ="GET_REFERENCE";

//bookheader
export const STRATEGY_LIST ="STRATEGY_LIST";
//策略按钮列表
// export const STRATEGY_BTN_LIST ="STRATEGY_BTN_LIST";

//选中按钮名称
export const BTN_NAME = "BTN_NAME";
export const BTN_INDEX ="BTN_INDEX";

//order book 参数列表
export const PARAM_LIST ="PARAM_LIST";
export const SET_CURRENT_STRATEGY ="SET_CURRENT_STRATEGY";

export const FIND_PENDING ="FIND_PENDING";
export const QUOTE_SOURCE ="QUOTE_SOURCE";

//trade order list
export const FIND_REALTIME_ORDER="FIND_REALTIME_ORDER";
export const QUOTE_ID ="QUOTE_ID";
export const QUOTE_MESSAGE ="QUOTE_MESSAGE";
export const QUOTE_RFQ ="QUOTE_RFQ";

//头寸
export const POSITION_LIST = "POSITION_LIST";
export const POSITION_LIST_LOADING = "POSITION_LIST_LOADING";
export const MARKET_PRICE = "MARKET_PRICE";
export const REFERENCE_PRICE = "REFERENCE_PRICE";
export const CCYPOSI_LIST = "CCYPOSI_LIST";
export const CCYPOSI_LIST_LOADING = "CCYPOSI_LIST_LOADING";

//CounterParty
export const COUNTERPARTY_LIST = "COUNTERPARTY_LIST";
export const COUNTER_LIST_LOADING = "COUNTER_LIST_LOADING";
//自动平盘
export const HEDGE_LIST = "HEDGE_LIST";
export const HEDGE_LIST_LOADING = "HEDGE_LIST_LOADING";
export const SAVE_HEDGE_LIST = "SAVE_HEDGE_LIST";
export const HEDGE_LIST_UNSAVED = "HEDGE_LIST_UNSAVED";
export const HEDGE_SELECT_VALUE = "HEDGE_SELECT_VALUE";
//自动报价
export const CLIENT_FLOW_LIST = "CLIENT_FLOW_LIST";
export const CLIENT_FLOW_LIST_LOADING = "CLIENT_FLOW_LIST_LOADING";
export const CLIENT_FLOW_LIST_UNSAVED = "CLIENT_FLOW_LIST_UNSAVED";
export const CLIENT_FLOW_SELECT_VALUE = "CLIENT_FLOW_SELECT_VALUE";
//手动报价
export const MANUAL_QUOTE_LIST = "MANUAL_QUOTE_LIST";
export const MANUAL_QUOTE_LIST_LOADING = "MANUAL_QUOTE_LIST_LOADING";
export const SAVE_QUOTE_OUTPUT = "SAVE_QUOTE_OUTPUT";

//交易订单
export const TRADE_ORDER_LIST_LOADING = "TRADE_ORDER_LIST_LOADING";

// 手动交易
export const MANUAL_TRADING_QUOTEREQUEST = "MANUAL_TRADING_QUOTEREQUEST";
export const FIND_TODAY_QUOTE_REQUEST = "FIND_TODAY_QUOTE_REQUEST";
export const SAVE_MANUAL_REQUEST_INFO = "SAVE_MANUAL_REQUEST_INFO";
export const FIND_TODAY_ORDER = "FIND_TODAY_ORDER";
export const SET_QUOTE_REQUEST_ID = "SET_QUOTE_REQUEST_ID";
export const PLACE_ORDER = "PLACE_ORDER";

export const CHANGE_SHOW_CLIENTFLOW = "CHANGE_SHOW_CLIENTFLOW";
export const CHANGE_SHOW_RISKMONITOR = "CHANGE_SHOW_RISKMONITOR";
export const CHANGE_SHOW_TRADING = "CHANGE_SHOW_TRADING";
export const CHANGE_SHOW_BLOTTER = "CHANGE_SHOW_BLOTTER";

//风险->市场风险监测监测
export const MARKET_RISK_LOADING = "MARKET_RISK_LOADING";
export const MARKET_RISK_UNSAVED = "MARKET_RISK_UNSAVED";
export const MARKET_RISK_SELECT_VALUE = "MARKET_RISK_SELECT_VALUE";
export const MARKET_RISK_LIST = "MARKET_RISK_LIST";

//风险->操作风险监测监测
export const OPERATION_RISK_LOADING = "OPERATION_RISK_LOADING";
export const OPERATION_RISK_UNSAVED = "OPERATION_RISK_UNSAVED";
export const OPERATION_RISK_SELECT_VALUE = "OPERATION_RISK_SELECT_VALUE";
export const OPERATION_RISK_LIST = "OPERATION_RISK_LIST";

export const CHANGE_SHOW_MARKET = "CHANGE_SHOW_MARKET";
export const CHANGE_SHOW_OPERATION = "CHANGE_SHOW_OPERATION";

//授信
export const COUNTER_PARTY_LOADING = "COUNTER_PARTY_LOADING";
export const COUNTER_PARTY_LIST = "COUNTER_PARTY_LIST";
export const CPTY_GROUP_LOADING = "CPTY_GROUP_LOADING";
export const CPTY_GROUP_LIST = "CPTY_GROUP_LIST";

export const MARKET_RISK_STATUS = "MARKET_RISK_STATUS";
export const RISK_ALERT = "RISK_ALERT";

export const CURRENT_GROUP = "CURRENT_GROUP";
export const SELECTED_CPTY = "SELECTED_CPTY";

export const ORDER_BOOK_VALUE = "ORDER_BOOK_VALUE";
export const SOCKET_CONNECTED = "SOCKET_CONNECTED";

export const MARKET_DATA = "MARKET_DATA";
export const APPLIED_MARKET = "APPLIED_MARKET";

export const MARKET_PRICE_MSG = "MARKET_PRICE_MSG";
export const MARKET_PRICE_ALL = "MARKET_PRICE_ALL";

export const INPUT_INFO = "INPUT_INFO";

export const LIQUIDITY_LIST = "LIQUIDITY_LIST";
export const LIQUIDITY_LIST_LOADING = "LIQUIDITY_LIST_LOADING";
export const L_SYMBOL_LIST = "L_SYMBOL_LIST";
export const L_SYMBOL_LIST_LOADING = "L_SYMBOL_LIST_LOADING";
export const L_SYMBOL_LIST_COPY_LOADING = "L_SYMBOL_LIST_COPY_LOADING";
export const MARKET_PRICE_LIQUIDITY = "MARKET_PRICE_LIQUIDITY";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const GET_SYSTEM_ALERT = "GET_SYSTEM_ALERT";

export const MARKET_SELECT_VALUE = "MARKET_SELECT_VALUE";
export const OPERATION_SELECT_VALUE = "OPERATION_SELECT_VALUE";

export const LIQUIDITY_REFERENCE = "LIQUIDITY_REFERENCE";

export const FIND_EXECUTION_BY_ORDER_ID = "FIND_EXECUTION_BY_ORDER_ID";
